#!/usr/bin/env python3
"""
Test Swiss pairing algorithm with specific R1 results
"""

from prediction_algorithm import MajorPredictor
from team_data import TEAMS_DATA, ROUND_1_MATCHUPS, INITIAL_SEEDING


def main():
    predictor = MajorPredictor()

    print("=" * 100)
    print("TESTING SWISS PAIRING - Custom R1 Results".center(100))
    print("=" * 100)
    print()

    print("INITIAL SEEDING (used for Swiss pairings):")
    print("-" * 100)
    for i, team in enumerate(INITIAL_SEEDING, 1):
        strength = predictor.calculate_team_strength(team)
        print(f"{i:>2}. {team:<20} (Strength: {strength:5.2f})")
    print()

    # Define specific R1 winners based on user input
    r1_results = {
        "Astralis": "win",      # beat NiP
        "NiP": "loss",
        "3DMAX": "win",         # beat fnatic
        "fnatic": "loss",
        "Passion UA": "win",    # beat FaZe
        "FaZe": "loss",
        "PARIVISION": "loss",   # lost to TYLOO
        "TYLOO": "win",
        "NAVI": "win",          # beat FlyQuest
        "FlyQuest": "loss",
        "Aurora": "win",        # beat M80
        "M80": "loss",
        "MIBR": "win",          # beat Imperial
        "Imperial": "loss",
        "Liquid": "win",        # beat B8
        "B8": "loss"
    }

    print("ROUND 1 RESULTS (as specified):")
    print("-" * 100)

    winners_1_0 = []
    losers_0_1 = []

    for team1, team2 in ROUND_1_MATCHUPS:
        result1 = r1_results[team1]
        result2 = r1_results[team2]

        if result1 == "win":
            winner = team1
            loser = team2
        else:
            winner = team2
            loser = team1

        winners_1_0.append(winner)
        losers_0_1.append(loser)

        strength1 = predictor.calculate_team_strength(team1)
        strength2 = predictor.calculate_team_strength(team2)

        print(f"{team1:<20} vs {team2:<20}")
        print(f"  → Winner: {winner:<20} (Str: {predictor.calculate_team_strength(winner):5.2f})")
        print()

    # Create records dict
    records = {}
    for team in winners_1_0:
        records[team] = {'wins': 1, 'losses': 0}
    for team in losers_0_1:
        records[team] = {'wins': 0, 'losses': 1}

    active_teams = set(winners_1_0 + losers_0_1)

    print("\n" + "=" * 100)
    print("ROUND 2 MATCHUPS (Generated by Swiss Pairing Algorithm)".center(100))
    print("=" * 100)
    print()

    # Sort by strength for display
    winners_sorted = sorted(winners_1_0, key=lambda t: predictor.calculate_team_strength(t), reverse=True)
    losers_sorted = sorted(losers_0_1, key=lambda t: predictor.calculate_team_strength(t), reverse=True)

    print("Teams with 1-0 record (8 teams):")
    for team in winners_sorted:
        strength = predictor.calculate_team_strength(team)
        print(f"  {team:<20} (Strength: {strength:5.2f})")
    print()

    print("Teams with 0-1 record (8 teams):")
    for team in losers_sorted:
        strength = predictor.calculate_team_strength(team)
        print(f"  {team:<20} (Strength: {strength:5.2f})")
    print()

    # Use Swiss pairing algorithm
    matchups_r2 = predictor._create_swiss_pairings(records, active_teams)

    print("-" * 100)
    print("GENERATED ROUND 2 MATCHUPS:")
    print("-" * 100)
    print()

    # Separate by bracket
    matchups_1_0 = []
    matchups_0_1 = []

    for team1, team2 in matchups_r2:
        if team1 in winners_1_0:
            matchups_1_0.append((team1, team2))
        else:
            matchups_0_1.append((team1, team2))

    print("🏆 1-0 BRACKET:")
    print()
    for i, (team1, team2) in enumerate(matchups_1_0, 1):
        str1 = predictor.calculate_team_strength(team1)
        str2 = predictor.calculate_team_strength(team2)
        print(f"{i}. {team1:<20} (Str: {str1:5.2f}) vs {team2:<20} (Str: {str2:5.2f})")
    print()

    print("💀 0-1 BRACKET:")
    print()
    for i, (team1, team2) in enumerate(matchups_0_1, 1):
        str1 = predictor.calculate_team_strength(team1)
        str2 = predictor.calculate_team_strength(team2)
        print(f"{i}. {team1:<20} (Str: {str1:5.2f}) vs {team2:<20} (Str: {str2:5.2f})")
    print()

    print("=" * 100)
    print("\n✅ Swiss pairing algorithm working correctly!")
    print("   - Teams with same record are paired together")
    print("   - 1-0 teams play each other")
    print("   - 0-1 teams play each other")
    print()


if __name__ == "__main__":
    main()
