"""
Central data for IEM Cologne Major 2026 predictions.

All values that are expected to change between events, stages, ranking updates,
roster updates, or model tuning live here. Prediction code should import from
this file instead of hardcoding event-specific data.

Source snapshot:
- HLTV IEM Cologne Major 2026 Stage 1 preview, checked on 2026-06-01.
- HLTV Valve global ranking, checked on 2026-06-01.
"""

from model_config import PREDICTION_WEIGHTS
from official_data import OFFICIAL_SOURCES, STAGE1_OFFICIAL_RANKS, STAGE1_OFFICIAL_ROUND_1_MATCHUPS

EVENT = {
    "name": "IEM Cologne Major 2026",
    "location": "Cologne, Germany",
    "prize_pool": "$1,250,000",
    "teams": 32,
    "start_date": "2026-06-02",
    "end_date": "2026-06-21",
    "source_url": OFFICIAL_SOURCES["event_hub"],
    "notes": (
        "32-team Major invited via Valve Regional Standings. Stage 1, Stage 2 "
        "and Stage 3 are Swiss stages; each feeds eight teams into the next."
    ),
}

DEFAULT_STAGE = "stage1"

STAGES = {
    "stage1": {
        "name": "Stage 1",
        "date_range": "2026-06-02 to 2026-06-05",
        "complete": True,
        "record_key": "stage_entry_record",
        "record_label": "Entry",
        "rank_label": "HLTV/VRS",
        "qualified_from": None,
        "qualifier_slots_to_next_stage": 8,
        "round_1_matchups": STAGE1_OFFICIAL_ROUND_1_MATCHUPS,
        "teams": {
            "GamerLegion": {
                "source": "Stage 1 invite",
                "event_seed": 12,
                "hltv_rank": 11,
                "valve_rank": 12,
                "stage_entry_record": "N/A",
                "momentum": "excellent",
                "form_score": 8.3,
                "upset_potential": "low",
                "consistency": 7.7,
                "players": ["Snax", "REZ", "Tauson", "PR", "hypex"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "BIG": {
                "source": "Stage 1 invite",
                "event_seed": 26,
                "hltv_rank": 32,
                "valve_rank": 26,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.2,
                "upset_potential": "medium",
                "consistency": 6.4,
                "players": ["tabseN", "JDC", "faveN", "blameF", "gr1ks"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "BetBoom": {
                "source": "Stage 1 invite",
                "event_seed": 18,
                "hltv_rank": 17,
                "valve_rank": 18,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 7.8,
                "upset_potential": "high",
                "consistency": 6.5,
                "players": ["Boombl4", "zorte", "d1Ledez", "Magnojez", "FL4MUS"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026; d1Ledez starts while S1ren joins later.",
            },
            "B8": {
                "source": "Stage 1 invite",
                "event_seed": 16,
                "hltv_rank": 16,
                "valve_rank": 16,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.3,
                "upset_potential": "high",
                "consistency": 6.6,
                "players": ["alex666", "npl", "kensizor", "esenthial", "s1zzi"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "HEROIC": {
                "source": "Stage 1 invite",
                "event_seed": 23,
                "hltv_rank": 23,
                "valve_rank": 23,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 6.8,
                "upset_potential": "medium",
                "consistency": 6.4,
                "players": ["xfl0ud", "nilo", "susp", "Chr1zN", "yxngstxr"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "SINNERS": {
                "source": "Stage 1 invite",
                "event_seed": 28,
                "hltv_rank": 27,
                "valve_rank": 28,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.0,
                "upset_potential": "high",
                "consistency": 7.2,
                "players": ["beastik", "SHOCK", "MoDo", "kisserek", "stressarN"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "M80": {
                "source": "Stage 1 invite",
                "event_seed": 29,
                "hltv_rank": 24,
                "valve_rank": 29,
                "stage_entry_record": "N/A",
                "momentum": "moderate",
                "form_score": 6.2,
                "upset_potential": "high",
                "consistency": 6.2,
                "players": ["slaxz-", "Swisher", "s1n", "JBa", "Lake"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "NRG": {
                "source": "Stage 1 invite",
                "event_seed": 43,
                "hltv_rank": 34,
                "valve_rank": 43,
                "stage_entry_record": "N/A",
                "momentum": "shaky",
                "form_score": 5.4,
                "upset_potential": "medium",
                "consistency": 5.2,
                "players": ["nitr0", "Sonic", "oSee", "Grim", "br0"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "Sharks": {
                "source": "Stage 1 invite",
                "event_seed": 38,
                "hltv_rank": 51,
                "valve_rank": 38,
                "stage_entry_record": "N/A",
                "momentum": "moderate",
                "form_score": 5.9,
                "upset_potential": "high",
                "consistency": 5.7,
                "players": ["gafolo", "koala", "maxxkor", "rdnzao", "doc"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "Gaimin Gladiators": {
                "source": "Stage 1 invite",
                "event_seed": 51,
                "hltv_rank": 46,
                "valve_rank": 51,
                "stage_entry_record": "N/A",
                "momentum": "shaky",
                "form_score": 5.2,
                "upset_potential": "high",
                "consistency": 5.0,
                "players": ["fer", "HEN1", "NEKIZ", "Luken", "JOTA"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "MIBR": {
                "source": "Stage 1 invite",
                "event_seed": 19,
                "hltv_rank": 29,
                "valve_rank": 19,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.4,
                "upset_potential": "high",
                "consistency": 6.6,
                "players": ["LNZ", "brnz4n", "insani", "venomzera", "kl1m"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "Liquid": {
                "source": "Stage 1 invite",
                "event_seed": 36,
                "hltv_rank": 25,
                "valve_rank": 36,
                "stage_entry_record": "N/A",
                "momentum": "shaky",
                "form_score": 5.5,
                "upset_potential": "high",
                "consistency": 5.2,
                "players": ["NAF", "EliGE", "malbsMd", "siuhy", "ultimate"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "TYLOO": {
                "source": "Stage 1 invite",
                "event_seed": 27,
                "hltv_rank": 31,
                "valve_rank": 27,
                "stage_entry_record": "N/A",
                "momentum": "moderate",
                "form_score": 6.1,
                "upset_potential": "very high",
                "consistency": 5.9,
                "players": ["JamYoung", "Jee", "Mercury", "Moseyuh", "Zero"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "Lynn Vision": {
                "source": "Stage 1 invite",
                "event_seed": 25,
                "hltv_rank": 45,
                "valve_rank": 25,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 6.4,
                "upset_potential": "very high",
                "consistency": 5.9,
                "players": ["Westmelon", "z4KR", "Starry", "EmiliaQAQ", "C4LLM3SU3"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "THUNDER dOWNUNDER": {
                "source": "Stage 1 invite",
                "event_seed": 56,
                "hltv_rank": 80,
                "valve_rank": 56,
                "stage_entry_record": "N/A",
                "momentum": "moderate",
                "form_score": 5.4,
                "upset_potential": "very high",
                "consistency": 4.7,
                "players": ["dexter", "Liazz", "aliStair", "asap", "TjP"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
            "FlyQuest": {
                "source": "Stage 1 invite",
                "event_seed": 74,
                "hltv_rank": 58,
                "valve_rank": 74,
                "stage_entry_record": "N/A",
                "momentum": "shaky",
                "form_score": 5.0,
                "upset_potential": "high",
                "consistency": 4.8,
                "players": ["jks", "INS", "Vexite", "nettik", "story"],
                "notes": "Stage 1 team listed by HLTV for Cologne 2026.",
            },
        },
    },
    "stage2": {
        "name": "Stage 2",
        "date_range": "2026-06-06 to 2026-06-09",
        "complete": False,
        "record_key": "stage_entry_record",
        "record_label": "Entry",
        "rank_label": "VRS seed proxy",
        "qualified_from": "stage1",
        "qualifier_slots_from_previous_stage": 8,
        "qualifier_slots_to_next_stage": 8,
        "teams": {
            "Spirit": {
                "source": "Stage 2 invite",
                "event_seed": 9,
                "hltv_rank": 3,
                "valve_rank": 2,
                "stage_entry_record": "N/A",
                "momentum": "excellent",
                "form_score": 9.2,
                "upset_potential": "low",
                "consistency": 8.8,
                "players": ["sh1ro", "magixx", "tN1R", "zont1x", "donk"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "Astralis": {
                "source": "Stage 2 invite",
                "event_seed": 10,
                "hltv_rank": 12,
                "valve_rank": 10,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 8.0,
                "upset_potential": "low",
                "consistency": 7.8,
                "players": ["HooXi", "phzy", "jabbi", "Staehr", "ryu"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "G2": {
                "source": "Stage 2 invite",
                "event_seed": 11,
                "hltv_rank": 13,
                "valve_rank": 13,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 7.9,
                "upset_potential": "medium",
                "consistency": 7.4,
                "players": ["huNter-", "NertZ", "SunPayus", "HeavyGod", "MATYS"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "FUT": {
                "source": "Stage 2 invite",
                "event_seed": 12,
                "hltv_rank": 14,
                "valve_rank": 12,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.7,
                "upset_potential": "medium",
                "consistency": 7.2,
                "players": ["dem0n", "lauNX", "Krabeni", "cmtry", "dziugss"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "Monte": {
                "source": "Stage 2 invite",
                "event_seed": 13,
                "hltv_rank": 23,
                "valve_rank": 21,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.1,
                "upset_potential": "medium",
                "consistency": 6.8,
                "players": ["Rainwaker", "Bymas", "afro", "Gizmy", "AZUWU"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "9z": {
                "source": "Stage 2 invite",
                "event_seed": 14,
                "hltv_rank": 21,
                "valve_rank": 15,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.6,
                "upset_potential": "medium",
                "consistency": 7.0,
                "players": ["max", "dgt", "meyern", "luchov", "HUASOPEEK"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "paiN": {
                "source": "Stage 2 invite",
                "event_seed": 15,
                "hltv_rank": 18,
                "valve_rank": 19,
                "stage_entry_record": "N/A",
                "momentum": "good",
                "form_score": 7.4,
                "upset_potential": "medium",
                "consistency": 7.0,
                "players": ["vsm", "biguzera", "piriajr", "saffee", "snow"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
            "Legacy": {
                "source": "Stage 2 invite",
                "event_seed": 16,
                "hltv_rank": 9,
                "valve_rank": 6,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.0,
                "upset_potential": "medium",
                "consistency": 7.5,
                "players": ["arT", "dumau", "latto", "n1ssim", "saadzin"],
                "notes": "Direct Stage 2 team listed by HLTV for Cologne 2026.",
            },
        },
    },
    "stage3": {
        "name": "Stage 3",
        "date_range": "2026-06-11 to 2026-06-15",
        "complete": False,
        "record_key": "stage_entry_record",
        "record_label": "Entry",
        "rank_label": "VRS seed proxy",
        "qualified_from": "stage2",
        "qualifier_slots_from_previous_stage": 8,
        "qualifier_slots_to_next_stage": 8,
        "teams": {
            "Vitality": {
                "source": "Stage 3 invite",
                "event_seed": 1,
                "hltv_rank": 1,
                "valve_rank": 1,
                "stage_entry_record": "N/A",
                "momentum": "excellent",
                "form_score": 9.8,
                "upset_potential": "very low",
                "consistency": 9.5,
                "players": ["apEX", "ropz", "ZywOo", "flameZ", "mezii"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "Natus Vincere": {
                "source": "Stage 3 invite",
                "event_seed": 2,
                "hltv_rank": 2,
                "valve_rank": 4,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 9.0,
                "upset_potential": "very low",
                "consistency": 8.8,
                "players": ["Aleksib", "iM", "b1t", "w0nderful", "makazze"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "PARIVISION": {
                "source": "Stage 3 invite",
                "event_seed": 3,
                "hltv_rank": 10,
                "valve_rank": 14,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.0,
                "upset_potential": "low",
                "consistency": 7.6,
                "players": ["Jame", "BELCHONOKK", "xiELO", "nota", "zweih"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "Aurora": {
                "source": "Stage 3 invite",
                "event_seed": 4,
                "hltv_rank": 6,
                "valve_rank": 8,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.6,
                "upset_potential": "low",
                "consistency": 8.2,
                "players": ["MAJ3R", "XANTARES", "woxic", "soulfly", "Wicadia"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "Falcons": {
                "source": "Stage 3 invite",
                "event_seed": 5,
                "hltv_rank": 4,
                "valve_rank": 3,
                "stage_entry_record": "N/A",
                "momentum": "excellent",
                "form_score": 9.1,
                "upset_potential": "low",
                "consistency": 8.4,
                "players": ["karrigan", "NiKo", "TeSeS", "m0NESY", "kyousuke"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "MOUZ": {
                "source": "Stage 3 invite",
                "event_seed": 6,
                "hltv_rank": 7,
                "valve_rank": 5,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.4,
                "upset_potential": "low",
                "consistency": 7.8,
                "players": ["torzsi", "Spinx", "jL", "xertioN", "xelex"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "FURIA": {
                "source": "Stage 3 invite",
                "event_seed": 7,
                "hltv_rank": 5,
                "valve_rank": 11,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.7,
                "upset_potential": "medium",
                "consistency": 8.2,
                "players": ["FalleN", "yuurih", "YEKINDAR", "KSCERATO", "molodoy"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
            "The MongolZ": {
                "source": "Stage 3 invite",
                "event_seed": 8,
                "hltv_rank": 8,
                "valve_rank": 7,
                "stage_entry_record": "N/A",
                "momentum": "very good",
                "form_score": 8.5,
                "upset_potential": "medium",
                "consistency": 8.1,
                "players": ["bLitz", "Techno", "mzinho", "910", "cobrazera"],
                "notes": "Direct Stage 3 team listed by HLTV for Cologne 2026.",
            },
        },
    },
}


def get_stage(stage_id=DEFAULT_STAGE):
    return STAGES[stage_id]


def get_stage_teams(stage_id=DEFAULT_STAGE):
    return STAGES[stage_id]["teams"]


def get_stage_seeding(stage_id=DEFAULT_STAGE):
    teams = get_stage_teams(stage_id)
    return sorted(teams, key=lambda team: teams[team]["event_seed"])


def build_seeded_round_1_matchups(stage_id=DEFAULT_STAGE):
    """Fallback Swiss opening pairings: best seed vs worst seed."""
    seeding = get_stage_seeding(stage_id)
    return [(seeding[i], seeding[-1 - i]) for i in range(len(seeding) // 2)]


def get_stage_matchups(stage_id=DEFAULT_STAGE):
    stage = STAGES[stage_id]
    if "round_1_matchups" in stage:
        return stage["round_1_matchups"]
    if len(stage["teams"]) >= 2:
        return build_seeded_round_1_matchups(stage_id)
    return []


for team, ranks in STAGE1_OFFICIAL_RANKS.items():
    STAGES["stage1"]["teams"][team].update(ranks)
